[project]
name = "authorization-server"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = ["confluent-kafka>=2.6.1", "loguru>=0.7.2", "pydantic>=2.9.2"]
